Лабораторная работа №1

Тема: Решение систем линейных алгебраических уравнений (СЛАУ)

Цель работы: Изучить методы решения СЛАУ и особенности их алгоритмизации в
современных программных библиотеках NumPy, SciPy языка Python.

Вариант 10

Индивидуальное задание:
\begin{equation*}
 \begin{cases}
   -177x_1 + 160x_2 -186x_3 = 170\\
   180x_1 - 192x_2 + 185x_3 = -160\\
   -183x_1 + 175x_2 - 190x_3 = 180\\
 \end{cases}
\end{equation*}

**Часть первая**

Решить СЛАУ вручную по методу Гаусса

\begin{pmatrix}
        -177 & 160 & -186 & 170 \\
        180 & -192 & 185 & -160 \\
        -183 & 175 & - 190 & 180
    \end{pmatrix}

\begin{pmatrix}
        1 & -\frac{160}{177} & 1\frac{9}{177} & -\frac{170}{177} \\
        180 & -192 & 185 & -160 \\
        -183 & 175 & - 190 & 180
    \end{pmatrix}

\begin{pmatrix}
        1 & -\frac{160}{177} & 1\frac{9}{177} & -\frac{170}{177} \\
        0 & -29\frac{17}{59} & -4\frac{9}{59} & 12\frac{52}{59} \\
        0 & 9\frac{34}{59} &2\frac{18}{59} & 4\frac{14}{59}
    \end{pmatrix}

\begin{pmatrix}
        1 & -\frac{160}{177} & 1\frac{9}{177} & -\frac{170}{177} \\
        0 & 1 & \frac{245}{1728} & -\frac{95}{216} \\
        0 & 9\frac{34}{59} &2\frac{18}{59} & 4\frac{14}{59}
    \end{pmatrix}

\begin{pmatrix}
        1 & 0 & 1\frac{29}{162} & -1\frac{29}{81} \\
        0 & 1 & \frac{245}{1728} & -\frac{95}{216} \\
        0 & 0 & \frac{1637}{1728} & 8\frac{97}{216}
\end{pmatrix}

\begin{pmatrix}
        1 & 0 & 1\frac{29}{162} & -1\frac{29}{81} \\
        0 & 1 & \frac{245}{1728} & -\frac{95}{216} \\
        0 & 0 & 1 & 8\frac{1504}{1637}
\end{pmatrix}

\begin{pmatrix}
        1 & 0 & 0 & -11\frac{4289}{4911} \\
        0 & 1 & 0 & -1\frac{1153}{1637} \\
        0 & 0 & 1 & 8\frac{1504}{1637}
\end{pmatrix}

Ответ: $x_1 = -11\frac{4289}{4911} \approx -11.873346$, $x_2 = -1\frac{1153}{1637} \approx -1.704337$, $x_3 = 8\frac{1504}{1637} \approx 8.918754$

**Вторая часть**

Напишите и выполните короткие программы на языке Python для решения СЛАУ с использованием разных алгоритмических техник в интерактивном блокноте Jupyter

In [ ]:
import numpy as np

# Коэффициенты системы уравнений
A = np.array([[ -177, 160, -186],
              [180, -192, 185],
              [-183, 175, -190]], dtype=float)

# Вектор свободных членов
b = np.array([170, -160, 180], dtype=float)

def gauss(A, b):
    """
    Решение СЛАУ методом Гаусса.

    Метод Гаусса — классический алгоритм решения СЛАУ,
    основанный на преобразовании исходной системы к
    верхнетреугольной форме с последующим обратным ходом
    для нахождения решений.

    Параметры:
    - A (numpy.ndarray): Матрица коэффициентов СЛАУ.
      Должна быть квадратной (n x n) и невырожденной.
    - b (numpy.ndarray): Вектор свободных членов СЛАУ.
      Должен быть длины n, где n - количество уравнений в системе.

    Возвращает:
    - numpy.ndarray: Вектор решения x системы Ax = b.
      Имеет размерность n, соответствующую числу уравнений в системе.
    """
    numEquations = len(b)
    # Прямой ход
    for pivotRow in range(numEquations):
        for currentRow in range(pivotRow + 1, numEquations):
            factor = A[currentRow, pivotRow] / \
            A[pivotRow, pivotRow]
            for currentCol in range(pivotRow, numEquations):
                A[currentRow, currentCol] -= factor * \
                A[pivotRow, currentCol]
            b[currentRow] -= factor * b[pivotRow]
    # Обратный ход
    solutionVector = np.zeros(numEquations)
    for currentRow in range(numEquations - 1, -1, -1):
        sum_ax = 0
        for currentCol in range(currentRow + 1, numEquations):
            sum_ax += A[currentRow, currentCol] * \
            solutionVector[currentCol]
        solutionVector[currentRow] = (b[currentRow] - sum_ax) / \
        A[currentRow, currentRow]
    return solutionVector

print(gauss(A.copy(), b.copy()))


def gauss_elimination_with_partial_pivoting(matrix, vector):
    """
    Решает СЛАУ методом Гаусса с частичным выбором
    ведущего элемента. Этот метод улучшает точность вычислений
    за счет минимизации ошибок округления, выбирая в качестве
    ведущего элемента максимальный по модулю в текущем столбце.

    Параметры:
    - matrix (numpy.ndarray): квадратная матрица коэффициентов СЛАУ.
    - vector (numpy.ndarray): вектор свободных членов СЛАУ.

    Возвращает:
    - numpy.ndarray: вектор решения СЛАУ.
    """
    matrix_size = len(matrix)
    # Прямой ход
    for current_column in range(matrix_size):
        # Поиск максимального элемента в текущем столбце
        max_index = np.argmax(np.abs(matrix[current_column:,
                                            current_column])) + \
        current_column
        # Обмен строк в матрице и векторе свободных членов

        matrix[[current_column, max_index]], \
        vector[[current_column, max_index]] = \
        (
        matrix[[max_index, current_column]],
        vector[[max_index, current_column]],
        )

        for i in range(current_column + 1, matrix_size):
            factor = matrix[i][current_column] / \
            matrix[current_column][current_column]
            matrix[i, current_column:] -= factor * \
            matrix[current_column, current_column:]
            vector[i] -= factor * vector[current_column]

    # Обратный ход
    solution = np.zeros(matrix_size)
    for i in range(matrix_size - 1, -1, -1):
        solution[i] = (vector[i] - np.dot(matrix[i, i + 1:], \
        solution[i + 1:])) / matrix[i][i]
    return solution

print(gauss_elimination_with_partial_pivoting(A, b))


def lu_decomposition(matrix, vector):
    """
    Выполняет LU-разложение матрицы и решает СЛАУ с помощью
    этого разложения.

    LU-разложение преобразует матрицу A в произведение
    двух матриц: L (нижнетреугольная) и U (верхнетреугольная),
    что облегчает решение СЛАУ.

    Параметры:
    - matrix (numpy.ndarray): квадратная матрица коэффициентов СЛАУ.
    - vector (numpy.ndarray): вектор свободных членов СЛАУ.

    Возвращает:
    - numpy.ndarray: вектор решения СЛАУ.
    """
    matrix_size = len(matrix)
    L = np.zeros((matrix_size, matrix_size))
    U = np.zeros((matrix_size, matrix_size))

    # LU разложение
    for row in range(matrix_size):
        L[row, row] = 1
        for col in range(row, matrix_size):
            sum_upper = sum(L[row, sum_index] * U[sum_index, col] \
                        for sum_index in range(row))
            U[row, col] = matrix[row, col] - sum_upper
        for col in range(row + 1, matrix_size):
            sum_lower = sum(L[col, sum_index] * U[sum_index, row] \
                        for sum_index in range(row))
            L[col, row] = (matrix[col, row] - sum_lower) / U[row, row]

    # Решение Ly = b для y
    y = np.zeros(matrix_size)
    for row in range(matrix_size):
        y[row] = vector[row] - np.dot(L[row, :row], y[:row])

    # Решение Ux = y для x
    x = np.zeros(matrix_size)
    for row in range(matrix_size - 1, -1, -1):
        x[row] = (y[row] - np.dot(U[row, row + 1:], x[row + 1:])) / \
                 U[row, row]

    return x

print(lu_decomposition(A, b))

[-11.87334555  -1.7043372    8.91875382]
[-11.87334555  -1.7043372    8.91875382]
[-11.87334555  -1.7043372    8.91875382]


** Третье задание **

Изменить параметры индивидуального задания так, чтобы программа не справилась с решением.

In [5]:
# Коэффициенты системы уравнений
A = np.array([[ -177, 160, -186],
              [180e+50, -192, 185],
              [-183, 175, -190]], dtype=float)

# Вектор свободных членов
b = np.array([170, -160, 180], dtype=float)

print(gauss(A.copy(), b.copy()))
print(gauss_elimination_with_partial_pivoting(A, b))
print(lu_decomposition(A, b))

[-0.          0.54883721 -0.44186047]
[ 1.50671835e-51  5.48837209e-01 -4.41860465e-01]
[ 1.50671835e-51  5.48837209e-01 -4.41860465e-01]


При классическом методе Гаусса была потеряна точность решения, в отличие от LU-разложения и улучшенного метода Гаусса.

Вывод: в ходе лабораторной работы изучили методы решения СЛАУ (классический и улучшенный методы Гаусса и LU-разложение) и особенности их алгоритмизации в
современных программных библиотеках NumPy, SciPy языка Python. Классический метод Гаусса может привести к потери точности решения, переполнению.